# Configuraci칩n para GitHub Pages
title: "KoriApp - Soluciones de Pago Globales"
description: "Una plataforma moderna de pagos digitales que ofrece soluciones seguras, r치pidas y escalables"

# URL del sitio en GitHub Pages
url: "https://runeimport.github.io"
baseurl: "/KoriWeb"

# Configuraci칩n del tema
theme: minima

# Archivos a excluir
exclude:
  - .vscode/
  - .github/
  - .gitignore

# Procesamiento con Jekyll
markdown: kramdown
highlighter: rouge

# Plugins necesarios
plugins:
  - jekyll-relative-links

# Configuraci칩n de kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
