# Configuración simple para GitHub Pages
title: "KoriApp - Soluciones de Pago Globales"
description: "Una plataforma moderna de pagos digitales que ofrece soluciones seguras, rápidas y escalables"

# URL del sitio en GitHub Pages
url: "https://runeimport.github.io"
baseurl: "/KoriWeb"

# Excluir archivos innecesarios
exclude:
  - .vscode/
  - .github/
  - .gitignore
  - README.md
  - tareas.log
  - Tareas.txt

# Configuración básica de Jekyll
markdown: kramdown
highlighter: rouge

# Configuración de kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
