title: KoriRemover
description: Aplicación web para remover fondos de imágenes con IA
baseurl: "/KoriWeb/koriremover/docs"
url: "https://runeimport.github.io"

# Jekyll configuration
markdown: kramdown
highlighter: rouge
theme: minima

# Include and exclude
include:
  - index.html
  - README.md

exclude:
  - node_modules
  - vendor
